### PR TITLE
Use SIMD instructions for Base64Url encoding.

### PR DESCRIPTION
**Pull request by ycrumeyrolle**
Reuse @gfoidl work.

### CODE REVIEW

**Comment by ycrumeyrolle** [comment]
The `TryDecode` takes 0.8% of the JWT global decoding.
The `GetMaxDecodedLength` takes 0.58%. This method might be optimized...

**Comment by ycrumeyrolle** [comment]
> The `GetMaxDecodedLength` takes 0.58%. This method might be optimized...
Change the control flow, now takes about 0.03%.

**Comment by gfoidl** [comment]
I'd love to see the nuget-package used instead of copying the code :wink:
If there's something missing in the package or your perf-measures don't meet the expectations, file an issue, so that the product can be improved and every user can get the benefit of this improvement. That's the idea of open-source.

I've no problem with copying anyway. It's just about improving something that can be used by a broader audience, instead of island-solutions.

**Comment by ycrumeyrolle** [comment]
I am fully agree with you. The source code duplication may be temporary for this version. 
This is too painful to maintain, and there are too many perf tweaks.

Nevertheless this give me the opportunity the manipulate the code for my use case and to identify some rooms of improvement.
Don't worry, I have some issues ready to open for you 😄

**Comment by gfoidl** [comment]
Fine 👍 
Thanks for the update on this topic.

> Don't worry, I have some issues ready to open for you

Nice :smiley:
Let's see if we can adopt everything so it fits the needs and has super perf...

**Pull request merged**
